apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    isDefault: true
    jsonData:
      # Crée un lien cliquable "Voir dans Jaeger" sur chaque log contenant un traceId
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"([0-9a-f]{32})"'
          url: '${__value.raw}'
          datasourceUid: jaeger
          urlDisplayLabel: 'Voir dans Jaeger'

  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    isDefault: false
